server:
  port: 8085

spring:
  application:
    name: LOAN-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/loan_db
    username: root
    password: Manish@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
