server:
  port: 8088

spring:
  application:
    name: TRANSFER-MICROSERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/transfer_db
    username: root
    password: Manish@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

account:
  service:
    url: http://ACCOUNT-SERVICE  # name registered in Eureka
